project:
  type: website
  output-dir: ../wiki

website:
  title: "NLab Community"
  navbar:
    left:
      - text: "Scope Analysis"
        href: analyze_scope.qmd
      - text: "Listmode Analysis"
        href: analyze_listmode.qmd